name: 'Parse Terraform Output'
description: 'Parse Terraform Output Action'
inputs:
  outputFilePath:
    description: 'The path to the Terraform JSON output file.'
    required: true
  variables:
    description: 'The array of variables you wish to parse.'
    default: []
    required: true
  secrets:
    description: 'The array of secrets you wish to parse.'
    default: []
    required: true
runs:
  using: 'node16'
  main: 'main.js'
branding:
  icon: 'activity'
  color: 'blue'
